# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
xcode_workspace: DynamicAppConfigIOS/Example/DynamicAppConfig.xcworkspace
xcode_scheme: DynamicAppConfig-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- pod lib lint
